# Generated by Django 6.0a1 on 2025-10-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("moderated", "На модерации"),
                    ("published", "Опубликован"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
